import org.gradle.internal.impldep.org.fusesource.jansi.AnsiRenderer.test

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("fizzbuzz.java-application-conventions")
    id("java")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass.set("fizzbuzz.app.App")
}

tasks.withType<Test> {
    this.testLogging {
        this.showStandardStreams = true
    }
}