/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz.app;

import org.junit.jupiter.api.Test;

import java.io.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
class FizzbuzzTest {
    static String EXPECTED_OUTPUT = "fizzfizzbuzzfizzfizzbuzzfizzfizzfizzbuzzfizzfizzbuzzfizzfizzfizzbuzzfizzfizzbuzzfizzfizzfizzbuzzfizzfizzbuzzfizzfizzfizzbuzzfizzfizzbuzzfizzfizzfizzbuzzfizzfizzbuzzfizzfizzfizzbuzzfizzfizzbuzz";

    /*
     * Ensure the following rules are followed
     * For the numbers 1 to 100, print the numbers using the following rules:
     *      if the number is evenly divisible by 3, print "fizz"
     *      if the number is evenly divisible by 5, print "buzz"
     *      if the number is evenly divisible by 15, print "fizzbuzz"
     */
    @Test void testTotalOutput() {
        // redirect output so we can capture
        var ogSystemOut = System.out;
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(outputStream);
        System.setOut(ps);

        // execute the code
        App.main(null);

        // flush the stream, set out back to console, and compare the captured output
        System.out.flush();
        System.setOut(ogSystemOut);
        var actualOutput = outputStream.toString();
        System.out.println(actualOutput);

        assertEquals(EXPECTED_OUTPUT, actualOutput);
    }
}
